version: "3"
services:
  portainer:
    # replace username/repo:tag with your name and image details
    image: portainer/portainer
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      #resources:
      #  limits:
      #    cpus: "0.1"
      #    memory: 50M
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - roguenet
  #visualizer:
   # image: dockersamples/visualizer:stable
   # ports:
   #   - "8080:8080"
   # volumes:
   #   - "/var/run/docker.sock:/var/run/docker.sock"
   # deploy:
   #   placement:
   #     constraints: [node.role == manager]
   # networks:
   #   - webnet
volumes:
  portainer_data:
  
networks:
  roguenet: